#!/usr/bin/python3
"""Code that factorize as many numbers"""
from sys import argv


def factorize(value):
    """"descomposition of an int > 1"""
    x = 2

    if value < 2:
        return
    print()
    print(value, "<- Prior-Value")
    while value % x:
        x += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / x, x))
    print(value, "<- Post-Value")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize(value)
            line = file.readline()
except:
    pass
